# Generated by Django 4.2.13 on 2024-06-24 00:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la observación', max_length=50, verbose_name='Nombre de la observación')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la observación', max_length=254, verbose_name='Descripción de la observación')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Observaciones',
            },
        ),
    ]
