# Generated by Django 4.2.13 on 2024-07-02 20:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPresencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('decimallongitude', models.FloatField(null=True)),
                ('decimallatitude', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
